// lib/detector.js
// Heurísticas de detecção, em ordem de confiança:
// 1. type/autocomplete do input (sinal padronizado do browser, o mais confiável)
// 2. name/id contra padrões conhecidos
// 3. texto do <label> associado
// 4. placeholder
// 5. pistas de maxlength (11 -> cpf, 14 -> cnpj, 8/9 -> cep)
// 6. fallback: select/dropdown -> 'dropdown_generico', textarea -> 'texto_longo',
//    qualquer outra coisa -> 'palavra_aleatoria'
//
// Além de <input>/<select>/<textarea>, também varremos qualquer elemento
// com role="combobox" ou aria-haspopup="listbox" — é assim que componentes
// de UI (shadcn/Radix Select, Combobox baseado em cmdk, react-select, etc)
// marcam o "trigger" que abre a lista de opções. Ver lib/filler.js pra como
// esses campos são preenchidos.
(function () {
  const PATTERNS = [
    { type: 'cpf', re: /\bcpf\b/i },
    { type: 'cnpj', re: /\bcnpj\b/i },
    { type: 'cep', re: /\bcep\b|postal|zip/i },
    { type: 'telefone', re: /telefone|\bfone\b|celular|\bphone\b|\btel\b/i },
    { type: 'email', re: /e-?mail/i },
    { type: 'senha', re: /senha|password|\bpass\b/i },
    { type: 'estado', re: /\buf\b|estado(?!.*civil)|\bstate\b/i },
    { type: 'cidade', re: /cidade|munic[íi]pio|\bcity\b/i },
    { type: 'data_nascimento', re: /nasc|birth/i },
    { type: 'bairro', re: /bairro|neighbo[u]?rhood/i },
    { type: 'sobrenome', re: /sobrenome|apelido|last.?name|surname/i },
    { type: 'nome', re: /\bnome\b|first.?name|^name$/i },
    { type: 'numero_endereco', re: /n[uú]mero|^num$|house.?number/i },
    { type: 'endereco', re: /endere[cç]o|address|logradouro/i },
    { type: 'link', re: /\blink\b/i },
    { type: 'renda', re: /renda|sal[áa]rio|\bincome\b/i },
  ];

  // Padrões de id gerado automaticamente por hook de useId() de várias
  // libs (React 18 puro, Radix, react-aria/react-aria-components). Esses
  // ids mudam a cada load/build — dependem de quantos outros componentes
  // foram montados antes na árvore — então NUNCA são uma identidade
  // confiável pra persistir configuração entre reloads.
  function looksAutoGenerated(id) {
    if (!id) return false;
    if (id.startsWith('react-aria')) return true; // ex: react-aria5397725782-:r31:
    if (id.startsWith('radix-')) return true; // ex: radix-:r0:
    if (/^:r[0-9a-z]+:$/i.test(id)) return true; // useId() puro do React 18: ":r0:"
    return false;
  }

  // Tokens padronizados de autocomplete (HTML spec) -> nosso tipo interno.
  const AUTOCOMPLETE_MAP = {
    'cc-number': 'cartao_credito',
    tel: 'telefone',
    email: 'email',
    'postal-code': 'cep',
    'address-level1': 'estado',
    'address-level2': 'cidade',
    'address-line1': 'endereco',
    bday: 'data_nascimento',
    'given-name': 'nome',
    'family-name': 'sobrenome',
    name: 'nome',
  };

  function isCustomDropdownTrigger(el) {
    const tag = el.tagName.toLowerCase();
    if (tag === 'select') return false;
    const role = (el.getAttribute('role') || '').toLowerCase();
    return role === 'combobox' || el.getAttribute('aria-haspopup') === 'listbox';
  }

  function isFillable(el) {
    if (el.disabled || el.readOnly) return false;
    const tag = el.tagName.toLowerCase();
    if (tag === 'input') {
      const skip = ['hidden', 'submit', 'button', 'image', 'file', 'reset', 'checkbox', 'radio'];
      if (skip.includes((el.type || 'text').toLowerCase())) return false;
    }
    if (el.getAttribute('aria-disabled') === 'true') return false;
    if (el.closest('[aria-hidden="true"]')) return false;
    if (el.getClientRects().length === 0) return false; // display:none / não renderizado
    return true;
  }

  function labelTextFor(el) {
    if (el.id) {
      const byFor = document.querySelector(`label[for="${CSS.escape(el.id)}"]`);
      if (byFor) return byFor.textContent.trim();
    }
    const parentLabel = el.closest('label');
    if (parentLabel) return parentLabel.textContent.trim();

    // shadcn/ui (componentes Field + FieldLabel) normalmente não usa
    // for/id — o rótulo é só um elemento irmão dentro do mesmo wrapper
    // marcado com data-slot="field". Procura ali antes de desistir.
    const fieldWrapper = el.closest('[data-slot="field"]');
    if (fieldWrapper) {
      const fieldLabel = fieldWrapper.querySelector('[data-slot="field-label"]');
      if (fieldLabel) return fieldLabel.textContent.trim();
    }

    // outros design systems colocam o texto num elemento irmão anterior
    const prev = el.previousElementSibling;
    if (prev && prev.tagName !== 'INPUT' && prev.tagName !== 'SELECT') {
      return prev.textContent.trim();
    }
    return '';
  }

  function matchPatterns(text) {
    for (const { type, re } of PATTERNS) {
      if (re.test(text)) return type;
    }
    return null;
  }

  // Remove acento e deixa só letras/números/hífen — usado pra construir uma
  // key estável a partir do texto do label, quando o elemento não tem
  // name/id (comum em trigger de Select/Combobox de biblioteca de UI, onde
  // o valor mora no estado do React, não num atributo nativo do DOM).
  function slugify(text) {
    return (text || '')
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');
  }

  function detectByLength(el) {
    const maxLength = el.maxLength;
    if (maxLength === 11) return 'cpf';
    if (maxLength === 14) return 'cnpj';
    if (maxLength === 8 || maxLength === 9) return 'cep';
    return null;
  }

  function detectType(el, { isCustomDropdown = false } = {}) {
    const tag = el.tagName.toLowerCase();
    const inputType = (el.type || '').toLowerCase();

    if (inputType === 'email') return 'email';
    if (inputType === 'tel') return 'telefone';
    if (inputType === 'password') return 'senha';
    if (inputType === 'date') return 'data_generica';
    if (inputType === 'number') return 'numero';

    const autocomplete = (el.autocomplete || '').toLowerCase();
    if (AUTOCOMPLETE_MAP[autocomplete]) return AUTOCOMPLETE_MAP[autocomplete];

    const haystack = [el.name, el.id, el.placeholder, labelTextFor(el)].filter(Boolean).join(' ');
    const byPattern = matchPatterns(haystack);
    if (byPattern) return byPattern;

    const byLength = detectByLength(el);
    if (byLength) return byLength;

    if (tag === 'select' || isCustomDropdown) return 'dropdown_generico';
    if (tag === 'textarea') return 'texto_longo';
    return 'palavra_aleatoria';
  }

  function scanFields(root = document) {
    // Set evita duplicar um elemento que já bateu nas duas queries (ex: um
    // <input role="combobox"> de um Combobox com busca, tipo cmdk).
    const candidates = new Set([
      ...root.querySelectorAll('input, select, textarea'),
      ...root.querySelectorAll('[role="combobox"], [aria-haspopup="listbox"]'),
    ]);
    const nodes = Array.from(candidates).filter(isFillable);

    // Pra desambiguar dois campos sem name/id que caem no mesmo label+tag
    // (ex: dois Combobox "Cidade" diferentes na mesma página).
    const seenKeys = new Map();

    return nodes.map((el, idx) => {
      const isCustomDropdown = isCustomDropdownTrigger(el);
      const label = labelTextFor(el) || el.placeholder || `campo ${idx}`;

      // Prioridade de identidade pra persistir configuração entre reloads:
      // 1. name        -> mais confiável, quase nunca muda
      // 2. id           -> só se NÃO for um id auto-gerado (react-aria,
      //                    radix, useId() puro) — esses mudam a cada load
      // 3. label slugificado -> conteúdo estável, quando não há nem 1 nem 2
      let key = el.name || (el.id && !looksAutoGenerated(el.id) ? el.id : '');
      if (!key) {
        const base = `${el.tagName.toLowerCase()}:${slugify(label) || 'sem-rotulo'}`;
        const count = (seenKeys.get(base) || 0) + 1;
        seenKeys.set(base, count);
        key = count > 1 ? `${base}#${count}` : base;
      }

      return {
        el,
        key,
        label,
        tag: el.tagName.toLowerCase(),
        inputType: el.type || null,
        isDropdown: el.tagName.toLowerCase() === 'select' || isCustomDropdown,
        detectedType: detectType(el, { isCustomDropdown }),
      };
    });
  }

  window.__BRFF = window.__BRFF || {};
  window.__BRFF.detector = { scanFields, detectType, isFillable, isCustomDropdownTrigger };
})();
